/// English texts used ONLY when a key is missing from the strings the server sends.
/// The server always wins. Add a line here when a new key is used.
///
/// Missing keys are still recorded (see /dev/strings), so the backend team can add them.
const Map<String, String> kFallbackStrings = {
  // ── App frame ──
  'main_tabbar_home_label': 'Home',
  'main_tabbar_orders_label': 'Orders',
  'main_tabbar_products_label': 'Products',
  'main_tabbar_account_label': 'More',
  'settings_settings_title': 'Settings',
  'storedetails_storeanalytics_title': 'Store Analytics',
  'storedetails_storeanalytics_store_earnings_title': 'Store Earnings',
  'settings_settings_row_walletTransactions': 'Wallet Transactions',
  'settings_settings_row_cashoutRequest': 'CashOut Request',
  'settings_settings_row_categories_title': 'Categories',
  'settings_settings_row_options': 'Options',
  'settings_settings_row_store_profile_title': 'Store Profile',
  'settings_settings_row_store_timings_title': 'Store Timings',
  'settings_settings_section_financial_customer': 'Financial & Customer',
  'settings_settings_section_store_settings': 'Store Settings',
  'storedetails_storetimeslots_open': 'Open',
  'storedetails_storetimeslots_closed': 'Closed',
  'settings_settings_row_memberShip': 'MemberShip',
  'settings_settings_row_memberShipDesc': 'Purchase Your MemberShip',
  // ── Common ──
  'common_allscreen_something_went_wrong': 'Something went wrong',
  'common_allscreen_try_again': 'Try Again',
  'common_allscreen_cancel_button': 'Cancel',
  'common_allscreen_confirm_button': 'Confirm',
  'common_allscreen_loading': 'Loading…',
  'common_allscreen_connectionFailed': 'Connection Failed',
  'common_allscreen_email': 'Email',
  'common_allscreen_phone': 'Phone',
  'common_allscreen_continue': 'Continue...',
  'common_allscreen_verifying': 'Verifying...',
  'common_allscreen_change': 'Change',
  'common_allscreen_saveChanges': 'Save Changes',
  'common_allscreen_cancel_retry': 'Retry',
  'common_allscreen_enter': 'Enter',
  'common_allscreen_submitting': 'Submitting…',
  'common_formvalidation_required_error': 'This field is required',
  'common_formvalidation_email_invalid_error': 'Enter a valid email address',
  'common_formvalidation_phone_invalid_error': 'Enter a valid phone number',
  // ── Splash and welcome ──
  'auth_welcomeview_maintenance_retailManagementPlatform': 'Retail Management Platform',
  'auth_welcomeview_subtitle': 'The complete solution for managing your retail business',
  'auth_welcomeview_login_button': 'Login',
  'auth_welcomeview_sign_up_button': 'Signup',
  'auth_welcomeview_feature_analytics_title': 'Real-time Analytics',
  'auth_welcomeview_feature_inventory_title': 'Inventory Management',
  'auth_welcomeview_feature_team_title': 'Team Collaboration',
  'auth_welcomeview_maintenance_selectLanguage': 'Select Language',
  'auth_welcomeview_maintenance_choosePreferedLanguage': 'Choose your preferred language',
  'auth_welcomeview_maintenance_applyingLanguage': 'Applying language…',
  'auth_welcomeview_maintenance_appUnderMaintenance': 'App is under maintenance',
  'auth_welcomeview_maintenance_exitApp': 'Exit App.',
  'auth_welcomeview_maintenance_mandatoryUpdate': 'Mandatory Update',
  'auth_welcomeview_update_title': 'New Version Available',
  'auth_welcomeview_update_button_title': 'Update Now',
  'auth_welcomeview_update_do_it_later': 'Maybe Later',
  'auth_welcomeview_consent_dialog_title': 'Data & Privacy',
  'auth_welcomeview_consent_dialog_subtitle': 'It\'s important to understand what information\\\\nour app collects and use',
  'auth_welcomeview_consent_contact_list_phone_no': 'Contact list / Phone number',
  'auth_welcomeview_consent_contact_list_phone_no_info': 'The application gathers and retains the user\'s contact list and phone numbers for verification procedures and future logins. Additionally, it enables users to communicate with drivers during a ride',
  'auth_welcomeview_consent_email_id': 'Email ID',
  'auth_welcomeview_consent_email_id_info': 'The app collects and stores email addresses for sending updates to drivers and facilitating communication purposes',
  'auth_welcomeview_consent_image_information': 'Image information / Profile pic',
  'auth_welcomeview_consent_image_information_info': 'The application collects and securely stores the user\'s profile picture for verifying the user\'s identity.',
  'auth_welcomeview_consent_note': 'By tapping Agree, you accept our Privacy Policy and Terms of Service.',
  'auth_welcomeview_consent_agree_and_continue': 'I Agree & Continue',
  'auth_welcomeview_merchant_logout_title': 'Session Expired',
  'auth_welcomeview_merchant_logout_message': 'You have been logged out for your security. Please log in again to continue.',
  // ── Login ──
  'auth_loginscreen_welcomeBack': 'Welcome back',
  'auth_loginscreen_subtitle': 'Manage your store with ease',
  'auth_loginscreen_signInToYourAccount': 'Sign in to your account',
  'auth_loginscreen_email_title': 'Email Address',
  'auth_loginscreen_email_placeholder': 'your@email.com',
  'auth_loginscreen_phone_title': 'Phone Number',
  'auth_loginscreen_phone_placeholder': 'Enter phone number',
  'auth_loginscreen_password_title': 'Password',
  'auth_loginscreen_password_placeholder': 'Enter your password',
  'auth_loginscreen_forgotPassword': 'Forgot Password?',
  'auth_loginscreen_sign_in_button': 'Login',
  'auth_loginscreen_signingIn': 'Signing in…',
  'auth_loginscreen_sign_up_prompt': 'Don\'t have an account? ',
  'auth_loginscreen_sign_up_action': 'Sign Up',
  'auth_loginscreen_email_required': 'Email is required',
  'auth_loginscreen_email_invalid': 'Enter valid email',
  'auth_loginscreen_password_required': 'Password required',
  'auth_demostoresview_login_button': 'Demo Login',
  // ── Signup ──
  'auth_signupscreen_title': 'Create Account',
  'auth_signupscreen_subtitle': 'Join StoreHub and start managing',
  'auth_signupscreen_fillInYourInformationBelow': 'Fill in your information below',
  'auth_signupscreen_store_name_title': 'Store Name',
  'auth_signupscreen_store_name_placeholder': 'My Store',
  'auth_signupscreen_segmentType': 'Segment Type',
  'auth_signupscreen_select_segment_title': 'Select Segment',
  'auth_signupscreen_full_name_title': 'Full Name',
  'auth_signupscreen_full_name_placeholder': 'John Doe',
  'auth_signupscreen_email_title': 'Email Address',
  'auth_signupscreen_email_placeholder': 'your@email.com',
  'auth_signupscreen_country': 'Country',
  'auth_signupscreen_selectCountry': 'Select Country',
  'auth_signupscreen_searchCountry': 'Search country...',
  'auth_signupscreen_noCountriesFound': 'No countries found',
  'auth_signupscreen_phone_title': 'Phone Number',
  'auth_signupscreen_phone_placeholder': 'Enter phone number',
  'auth_signupscreen_password_title': 'Password',
  'auth_signupscreen_password_placeholder': 'Enter Password',
  'auth_signupscreen_confirm_password_title': 'Confirm Password',
  'auth_signupscreen_confirm_password_placeholder': 'Re-enter your password',
  'auth_signupscreen_passwordNotMatch': 'Passwords do not match',
  'auth_signupscreen_sponsorInfo': ' Sponsor Info ',
  'auth_signupscreen_sponsorName': 'Sponsor Name',
  'auth_signupscreen_sponsorNamePlaceHolder': '\\',
  'auth_signupscreen_sponsorEmail': 'Sponsor Email',
  'auth_signupscreen_sponsorEmailPlaceHolder': 'Enter sponsor email',
  'auth_signupscreen_continue_terms_prefix': 'By continuing, you agree to ',
  'auth_signupscreen_continue_terms_middle': ' and ',
  'auth_signupscreen_terms_text': 'Terms & Conditions',
  'auth_signupscreen_privacy_text': 'Privacy Policy',
  'auth_signupscreen_terms_required': 'Please accept terms & conditions first',
  'auth_signupscreen_create_account_button': 'Create Account',
  'auth_signupscreen_back_to_login': 'Back to Login',
  'auth_signupscreen_sign_in_prompt': 'Already have an account? Sign In',
  'auth_signupscreen_yourDetails': 'Your Details',
  'storedetails_storeprofile_store_details_title': 'Store Details',
  'storedetails_storeprofile_store_name_required': 'Store name is required',
  'storedetails_storeprofile_phone_required': 'Phone number required',
  'pos_possecurityscreen_title': 'Security',
  // ── Password recovery ──
  'auth_forgotpassword_forgotPassword': 'Forgot Password',
  'auth_forgotpassword_info': 'We\'ll send a verification code to reset your password',
  'auth_forgotpassword_email_title': 'Email Address',
  'auth_forgotpassword_phone_title': 'Phone Number',
  'auth_forgotpassword_email_placeholder': 'your@email.com',
  'auth_forgotpassword_phone_placeholder': 'Enter phone number',
  'auth_forgotpassword_email_required_error': 'Email is required',
  'auth_forgotpassword_email_invalid_error': 'Please enter a valid email',
  'auth_forgotpassword_sendVerificationCode': 'Send Verification Code',
  'auth_forgotpassword_back_to_login': 'Back to Login',
  'auth_verificationcode_verifyOtp': 'Verify Otp',
  'auth_verificationcode_enterOtpInstruction': 'Enter the 4-digit verification code sent to',
  'auth_verificationcode_resendCodeIn': 'Resend code in ',
  'auth_verificationcode_resend_code_button': 'Resend Code',
  'error_invalid_otp': 'Invalid OTP. Please try again.',
  'auth_resetpassword_changePassword': 'Change Password',
  'auth_resetpassword_new_password_title': 'New Password',
  'auth_resetpassword_new_password_placeholder': 'Enter your new password',
  'auth_resetpassword_passwordStrength': 'Password strength:',
  'auth_resetpassword_passwordRequirements': 'Password requirements',
  'auth_resetpassword_atLeast8Characters': 'At least 8 characters',
  'auth_resetpassword_oneUpperCaseLetter': 'One uppercase letter',
  'auth_resetpassword_oneNumber': 'One number',
  'auth_resetpassword_oneSpecialCharacter': 'One special character',
  'auth_resetpassword_confirm_password_title': 'Confirm Password',
  'auth_resetpassword_confirm_password_placeholder': 'Confirm your password',
  'auth_resetpassword_password_required_error': 'Password is required',
  'auth_resetpassword_password_mismatch_error': 'Passwords do not match',
  'auth_resetpassword_passwordMatch': 'Passwords match',
  'auth_resetpassword_updatePasswordButton': 'Update Password',
  // ── Preview and demo ──
  'auth_merchantlogin_header_title': 'Merchant Login',
  'auth_merchantlogin_pin_placeholder': 'Enter Merchant Pin',
  'auth_merchantlogin_preview_title': 'Preview Merchant Login',
  'auth_demostoresview_select_title': 'Select Store',
  'auth_demostoresview_select_subtitle': 'Select a demo store to explore the app.',
  'auth_demostoresview_food_segment': 'Food',
  'auth_demostoresview_grocery_segment': 'Grocery',
  'auth_demostoresview_noDemoUsersFound': 'No Demo Users Found',
  'auth_demostoresview_trySwitchingCategoryAbove': 'Try switching the category above',
  'auth_demostoresview_selected': 'Selected',
  'auth_demostoresview_tapToSelect': 'Tap to select',
  'auth_demostoresview_selectDemoAccount': 'Select a Demo Account',
  // ── Stripe and documents ──
  'stripeconnect_stripeconnect_selectImage': 'Select Image',
  'stripeconnect_stripeconnect_camera': 'Camera',
  'stripeconnect_stripeconnect_gallery': 'Gallery',
  'stripeconnect_stripeconnect_selectDate': 'Select Date',
  'stripeconnect_stripeconnect_noDocumentsRequired': 'No documents required',
  'stripeconnect_stripeconnect_youAreAllSet': 'You\'re all set!',
  'stripeconnect_stripeconnect_submit_button': 'Submit',
  'stripeconnect_stripeconnect_requiredDocuments': 'Required Documents',
  'stripeconnect_stripeconnect_fillAllTheFieldsBelow': 'Please fill all the fields below',
  'stripeconnect_stripeconnect_stripeVerification': 'Stripe Verification',
  'stripeconnect_stripeconnect_completeYourAccountSetup': 'Complete your account setup',
  'stripeconnect_stripeconnect_secureVerification': 'Secure Verification',
  'stripeconnect_stripeconnect_uploadSuccessful': 'Upload successful',
  'stripeconnect_stripeconnect_uploading': 'Uploading',
  'stripeconnect_stripeconnect_upload_title': 'Upload Stripe Document',
  'stripeconnect_stripeconnect_selectTypeAndUploadImage': 'Select type and upload images',
  'stripeconnect_stripeconnect_veriftyYourIndentiryWithStripe': 'Verify your identity with Stripe',
  'stripeconnect_stripeconnect_identityVerification': 'Identity Verification',
  'stripeconnect_stripeconnect_uploadClearLegibleImages': 'Upload clear, legible images of your document',
  'stripeconnect_stripeconnect_select_type_title': 'Select Document Type',
  'stripeconnect_stripeconnect_front_side_title': 'Front Side',
  'stripeconnect_stripeconnect_back_side_title': 'Back Side',
  'stripeconnect_stripeconnect_tapToUpload': 'Tap to upload',
  'stripeconnect_stripeconnect_cameraOrGallery': 'Camera or Gallery',
  // ── Home ──
  'main_storedashboard_business_summary_title': 'Business Summary',
  'main_storedashboard_completed_title': 'Completed',
  'main_storedashboard_good_afternoon': 'Good Afternoon! 🌤️',
  'main_storedashboard_good_evening': 'Good Evening! 🌆',
  'main_storedashboard_good_night': 'Good Night! 🌙',
  'main_storedashboard_in_progress_title': 'In Progress',
  'main_storedashboard_low_stock_alert_message': 'products running low',
  'main_storedashboard_low_stock_alert_title': 'Low Stock Alert',
  'main_storedashboard_merchant_earnings_title': 'Merchant Earning',
  'main_storedashboard_order_amount_title': 'Order Amount',
  'main_storedashboard_out_of_stock_message': 'products unavailable',
  'main_storedashboard_out_of_stock_title': 'Out of Stock',
  'main_storedashboard_pending_title': 'Pending',
  'main_storedashboard_products_count_title': 'Products Count',
  'main_storedashboard_quick_action_add_product': 'Add Product',
  'main_storedashboard_quick_action_analytics': 'Analytics',
  'main_storedashboard_quick_action_manage_stock': 'Manage Stock',
  'main_storedashboard_quick_action_orders': 'Orders',
  'main_storedashboard_quick_actions_title': 'Quick Actions',
  'main_storedashboard_sales_month_title': 'This Month',
  'main_storedashboard_sales_summary_title': 'Sales Summary',
  'main_storedashboard_sales_today_title': 'Today',
  'main_storedashboard_sales_week_title': 'This Week',
  'main_storedashboard_store_earnings_title': 'Store Earning',
  'main_storedashboard_store_status_closed': 'Store is closed',
  'main_storedashboard_store_status_closed_goodDay': 'Good Day! 👋',
  'main_storedashboard_store_status_open': 'Currently accepting orders',
  'main_storedashboard_store_status_title': 'Store Status',
  'main_storedashboard_subtitle': 'Here\'s what\'s happening at {store_name} today.',
  'main_storedashboard_totalOrders': 'Total Orders',
  // ── Orders list ──
  'orders_ordersscreen_title': 'Orders',
  'orders_ordersscreen_tab_new': 'New',
  'orders_ordersscreen_tab_preparing': 'Preparing',
  'orders_ordersscreen_tab_ready': 'Ready',
  'orders_ordersscreen_past_cancelled_tab_title': 'Cancelled',
  'orders_ordersscreen_past_rejected_tab_title': 'Rejected',
  'orders_ordersscreen_past_auto_expired_tab_title': 'Expired',
  'orders_ordersscreen_past_completed_tab_title': 'Completed',
  'orders_ordersscreen_tab_today': 'Today',
  'orders_ordersscreen_tab_upcoming': 'Upcoming',
  'orders_ordersscreen_filter_pending_process_title': 'Pending Process',
  'orders_ordersscreen_filter_pending_pickup_title': 'Pending Pickup Verification',
  'orders_ordersscreen_filter_on_the_way_title': 'On The Way Orders',
  'orders_ordersscreen_items_title': 'Items:',
  'orders_ordersscreen_payment_title': 'Payment',
  'emptystate_emptystate_no_orders_title': 'No Orders Yet',
  'emptystate_emptystate_no_orders_message1': 'Try switching the status filter\\nor pull down to refresh',
  // ── Order detail and actions ──
  'orders_orderdetail_order_items_title': 'Order Items',
  'orders_orderdetail_order_status_title': 'Order Status',
  'orders_orderdetail_payment_details_title': 'Payment Details',
  'orders_orderdetail_payment_status_label': 'Payment Status',
  'orders_orderdetail_total_amount_label': 'Total Amount',
  'orders_orderdetail_item_qty_prefix': 'Qty: ',
  'orders_orderdetail_additional_notes_title': 'Additional Notes',
  'orders_orderdetail_chooseHowToAssign': 'Choose how you want to assign\\n a delivery driver',
  'orders_orderdetail_drivers_failed_title': 'Failed to load drivers',
  'orders_orderdetail_drivers_no_available_title': 'No Driver Available',
  'orders_orderdetail_drivers_no_available_subtitle': 'Try automatic assignment instead',
  'orders_orderdetail_select_drivers_hint': 'Tap to select multiple drivers',
  'orders_orderdetail_pickup_verification_subtitle': 'Ask the driver to provide the code to verify driver',
  'orders_orderdetail_otp_label': 'Enter Otp',
  'orders_ordersscreen_payment_method_title': 'Payment Method',
  'orders_ordersscreen_customerInfo': 'Customer Information',
  'orders_ordersscreen_customer_role': 'Customer',
  'orders_ordersscreen_callLabel': 'Call',
  'orders_ordersscreen_delivery_driver_title': 'Delivery Driver',
  'orders_ordersscreen_cooking_instructions_title': 'Cooking Instructions',
  'orders_ordersscreen_additional_instructions_title': 'Additional Instructions',
  'orders_ordersscreen_invoice_title_text': 'Invoice',
  'orders_ordersscreen_automatic_title': 'Automatic',
  'orders_ordersscreen_automatic_message': 'System picks the nearest available driver',
  'orders_ordersscreen_manual_title': 'Manual',
  'orders_ordersscreen_manual_message': 'Browse and select a driver yourself',
  'orders_ordersscreen_pickup_verification_button': 'Pickup Verification',
  'orders_ordersscreen_verify_otp_button': 'Verify OTP',
  'orders_ordersscreen_invalid_otp_message': 'Invalid OTP. Please try again.',
  'orders_selectdrivers_title': 'Select Drivers',
  'orders_selectdrivers_order_prefix': 'ORD-',
  'orders_selectdrivers_assign_button': 'Assign Drivers',
};