/// English texts used ONLY when a key is missing from the strings the server sends.
/// The server always wins. Add a line here when a new key is used.
///
/// Missing keys are still recorded (see /dev/strings), so the backend team can add them.
const Map<String, String> kFallbackStrings = {
  // ── App frame ──
  'main_tabbar_home_label': 'Home',
  'main_tabbar_orders_label': 'Orders',
  'main_tabbar_products_label': 'Products',
  'main_tabbar_account_label': 'More',
  'main_tabbar_more_label': 'More',
  'settings_settings_title': 'Settings',
  'storedetails_storeanalytics_title': 'Store Analytics',
  'storedetails_storeanalytics_store_earnings_title': 'Store Earnings',
  'settings_settings_row_walletTransactions': 'Wallet Transactions',
  'settings_settings_row_cashoutRequest': 'CashOut Request',
  'settings_settings_row_categories_title': 'Categories',
  'settings_settings_row_options': 'Options',
  'settings_settings_row_store_profile_title': 'Store Profile',
  'settings_settings_row_store_timings_title': 'Store Timings',
  'settings_settings_section_financial_customer': 'Financial & Customer',
  'settings_settings_section_store_settings': 'Store Settings',
  'storedetails_storetimeslots_open': 'Open',
  'storedetails_storetimeslots_closed': 'Closed',
  'settings_settings_row_memberShip': 'MemberShip',
  'settings_settings_row_memberShipDesc': 'Purchase Your MemberShip',
  // ── Common ──
  'common_allscreen_something_went_wrong': 'Something went wrong',
  'common_allscreen_try_again': 'Try Again',
  'common_allscreen_cancel_button': 'Cancel',
  'common_allscreen_confirm_button': 'Confirm',
  'common_allscreen_loading': 'Loading…',
  'common_allscreen_connectionFailed': 'Connection Failed',
  'common_allscreen_email': 'Email',
  'common_allscreen_phone': 'Phone',
  'common_allscreen_continue': 'Continue...',
  'common_allscreen_verifying': 'Verifying...',
  'common_allscreen_change': 'Change',
  'common_allscreen_saveChanges': 'Save Changes',
  'common_allscreen_cancel_retry': 'Retry',
  'common_allscreen_enter': 'Enter',
  'common_allscreen_submitting': 'Submitting…',
  'common_formvalidation_required_error': 'This field is required',
  'common_formvalidation_email_invalid_error': 'Enter a valid email address',
  'common_formvalidation_phone_invalid_error': 'Enter a valid phone number',
  // ── Splash and welcome ──
  'auth_welcomeview_maintenance_retailManagementPlatform': 'Retail Management Platform',
  'auth_welcomeview_subtitle': 'The complete solution for managing your retail business',
  'auth_welcomeview_login_button': 'Login',
  'auth_welcomeview_sign_up_button': 'Signup',
  'auth_welcomeview_feature_analytics_title': 'Real-time Analytics',
  'auth_welcomeview_feature_inventory_title': 'Inventory Management',
  'auth_welcomeview_feature_team_title': 'Team Collaboration',
  'auth_welcomeview_maintenance_selectLanguage': 'Select Language',
  'auth_welcomeview_maintenance_choosePreferedLanguage': 'Choose your preferred language',
  'auth_welcomeview_maintenance_applyingLanguage': 'Applying language…',
  'auth_welcomeview_maintenance_appUnderMaintenance': 'App is under maintenance',
  'auth_welcomeview_maintenance_exitApp': 'Exit App.',
  'auth_welcomeview_maintenance_mandatoryUpdate': 'Mandatory Update',
  'auth_welcomeview_update_title': 'New Version Available',
  'auth_welcomeview_update_button_title': 'Update Now',
  'auth_welcomeview_update_do_it_later': 'Maybe Later',
  'auth_welcomeview_consent_dialog_title': 'Data & Privacy',
  'auth_welcomeview_consent_dialog_subtitle': 'It\'s important to understand what information\\\\nour app collects and use',
  'auth_welcomeview_consent_contact_list_phone_no': 'Contact list / Phone number',
  'auth_welcomeview_consent_contact_list_phone_no_info': 'The application gathers and retains the user\'s contact list and phone numbers for verification procedures and future logins. Additionally, it enables users to communicate with drivers during a ride',
  'auth_welcomeview_consent_email_id': 'Email ID',
  'auth_welcomeview_consent_email_id_info': 'The app collects and stores email addresses for sending updates to drivers and facilitating communication purposes',
  'auth_welcomeview_consent_image_information': 'Image information / Profile pic',
  'auth_welcomeview_consent_image_information_info': 'The application collects and securely stores the user\'s profile picture for verifying the user\'s identity.',
  'auth_welcomeview_consent_note': 'By tapping Agree, you accept our Privacy Policy and Terms of Service.',
  'auth_welcomeview_consent_agree_and_continue': 'I Agree & Continue',
  'auth_welcomeview_merchant_logout_title': 'Session Expired',
  'auth_welcomeview_merchant_logout_message': 'You have been logged out for your security. Please log in again to continue.',
  // ── Login ──
  'auth_loginscreen_welcomeBack': 'Welcome back',
  'auth_loginscreen_subtitle': 'Manage your store with ease',
  'auth_loginscreen_signInToYourAccount': 'Sign in to your account',
  'auth_loginscreen_email_title': 'Email Address',
  'auth_loginscreen_email_placeholder': 'your@email.com',
  'auth_loginscreen_phone_title': 'Phone Number',
  'auth_loginscreen_phone_placeholder': 'Enter phone number',
  'auth_loginscreen_password_title': 'Password',
  'auth_loginscreen_password_placeholder': 'Enter your password',
  'auth_loginscreen_forgotPassword': 'Forgot Password?',
  'auth_loginscreen_sign_in_button': 'Login',
  'auth_loginscreen_signingIn': 'Signing in…',
  'auth_loginscreen_sign_up_prompt': 'Don\'t have an account? ',
  'auth_loginscreen_sign_up_action': 'Sign Up',
  'auth_loginscreen_email_required': 'Email is required',
  'auth_loginscreen_email_invalid': 'Enter valid email',
  'auth_loginscreen_password_required': 'Password required',
  'auth_demostoresview_login_button': 'Demo Login',
  // ── Signup ──
  'auth_signupscreen_title': 'Create Account',
  'auth_signupscreen_subtitle': 'Join StoreHub and start managing',
  'auth_signupscreen_fillInYourInformationBelow': 'Fill in your information below',
  'auth_signupscreen_store_name_title': 'Store Name',
  'auth_signupscreen_store_name_placeholder': 'My Store',
  'auth_signupscreen_segmentType': 'Segment Type',
  'auth_signupscreen_select_segment_title': 'Select Segment',
  'auth_signupscreen_full_name_title': 'Full Name',
  'auth_signupscreen_full_name_placeholder': 'John Doe',
  'auth_signupscreen_email_title': 'Email Address',
  'auth_signupscreen_email_placeholder': 'your@email.com',
  'auth_signupscreen_country': 'Country',
  'auth_signupscreen_selectCountry': 'Select Country',
  'auth_signupscreen_searchCountry': 'Search country...',
  'auth_signupscreen_noCountriesFound': 'No countries found',
  'auth_signupscreen_phone_title': 'Phone Number',
  'auth_signupscreen_phone_placeholder': 'Enter phone number',
  'auth_signupscreen_password_title': 'Password',
  'auth_signupscreen_password_placeholder': 'Enter Password',
  'auth_signupscreen_confirm_password_title': 'Confirm Password',
  'auth_signupscreen_confirm_password_placeholder': 'Re-enter your password',
  'auth_signupscreen_passwordNotMatch': 'Passwords do not match',
  'auth_signupscreen_sponsorInfo': ' Sponsor Info ',
  'auth_signupscreen_sponsorName': 'Sponsor Name',
  'auth_signupscreen_sponsorNamePlaceHolder': '\\',
  'auth_signupscreen_sponsorEmail': 'Sponsor Email',
  'auth_signupscreen_sponsorEmailPlaceHolder': 'Enter sponsor email',
  'auth_signupscreen_continue_terms_prefix': 'By continuing, you agree to ',
  'auth_signupscreen_continue_terms_middle': ' and ',
  'auth_signupscreen_terms_text': 'Terms & Conditions',
  'auth_signupscreen_privacy_text': 'Privacy Policy',
  'auth_signupscreen_terms_required': 'Please accept terms & conditions first',
  'auth_signupscreen_create_account_button': 'Create Account',
  'auth_signupscreen_back_to_login': 'Back to Login',
  'auth_signupscreen_sign_in_prompt': 'Already have an account? Sign In',
  'auth_signupscreen_yourDetails': 'Your Details',
  'storedetails_storeprofile_store_details_title': 'Store Details',
  'storedetails_storeprofile_store_name_required': 'Store name is required',
  'storedetails_storeprofile_phone_required': 'Phone number required',
  'pos_possecurityscreen_title': 'Security',
  // ── Password recovery ──
  'auth_forgotpassword_forgotPassword': 'Forgot Password',
  'auth_forgotpassword_info': 'We\'ll send a verification code to reset your password',
  'auth_forgotpassword_email_title': 'Email Address',
  'auth_forgotpassword_phone_title': 'Phone Number',
  'auth_forgotpassword_email_placeholder': 'your@email.com',
  'auth_forgotpassword_phone_placeholder': 'Enter phone number',
  'auth_forgotpassword_email_required_error': 'Email is required',
  'auth_forgotpassword_email_invalid_error': 'Please enter a valid email',
  'auth_forgotpassword_sendVerificationCode': 'Send Verification Code',
  'auth_forgotpassword_back_to_login': 'Back to Login',
  'auth_verificationcode_verifyOtp': 'Verify Otp',
  'auth_verificationcode_enterOtpInstruction': 'Enter the 4-digit verification code sent to',
  'auth_verificationcode_resendCodeIn': 'Resend code in ',
  'auth_verificationcode_resend_code_button': 'Resend Code',
  'error_invalid_otp': 'Invalid OTP. Please try again.',
  'auth_resetpassword_changePassword': 'Change Password',
  'auth_resetpassword_new_password_title': 'New Password',
  'auth_resetpassword_new_password_placeholder': 'Enter your new password',
  'auth_resetpassword_passwordStrength': 'Password strength:',
  'auth_resetpassword_passwordRequirements': 'Password requirements',
  'auth_resetpassword_atLeast8Characters': 'At least 8 characters',
  'auth_resetpassword_oneUpperCaseLetter': 'One uppercase letter',
  'auth_resetpassword_oneNumber': 'One number',
  'auth_resetpassword_oneSpecialCharacter': 'One special character',
  'auth_resetpassword_confirm_password_title': 'Confirm Password',
  'auth_resetpassword_confirm_password_placeholder': 'Confirm your password',
  'auth_resetpassword_password_required_error': 'Password is required',
  'auth_resetpassword_password_mismatch_error': 'Passwords do not match',
  'auth_resetpassword_passwordMatch': 'Passwords match',
  'auth_resetpassword_updatePasswordButton': 'Update Password',
  // ── Preview and demo ──
  'auth_merchantlogin_header_title': 'Merchant Login',
  'auth_merchantlogin_pin_placeholder': 'Enter Merchant Pin',
  'auth_merchantlogin_preview_title': 'Preview Merchant Login',
  'auth_demostoresview_select_title': 'Select Store',
  'auth_demostoresview_select_subtitle': 'Select a demo store to explore the app.',
  'auth_demostoresview_food_segment': 'Food',
  'auth_demostoresview_grocery_segment': 'Grocery',
  'auth_demostoresview_noDemoUsersFound': 'No Demo Users Found',
  'auth_demostoresview_trySwitchingCategoryAbove': 'Try switching the category above',
  'auth_demostoresview_selected': 'Selected',
  'auth_demostoresview_tapToSelect': 'Tap to select',
  'auth_demostoresview_selectDemoAccount': 'Select a Demo Account',
  // ── Stripe and documents ──
  'stripeconnect_stripeconnect_selectImage': 'Select Image',
  'stripeconnect_stripeconnect_camera': 'Camera',
  'stripeconnect_stripeconnect_gallery': 'Gallery',
  'stripeconnect_stripeconnect_selectDate': 'Select Date',
  'stripeconnect_stripeconnect_noDocumentsRequired': 'No documents required',
  'stripeconnect_stripeconnect_youAreAllSet': 'You\'re all set!',
  'stripeconnect_stripeconnect_submit_button': 'Submit',
  'stripeconnect_stripeconnect_requiredDocuments': 'Required Documents',
  'stripeconnect_stripeconnect_fillAllTheFieldsBelow': 'Please fill all the fields below',
  'stripeconnect_stripeconnect_stripeVerification': 'Stripe Verification',
  'stripeconnect_stripeconnect_completeYourAccountSetup': 'Complete your account setup',
  'stripeconnect_stripeconnect_secureVerification': 'Secure Verification',
  'stripeconnect_stripeconnect_uploadSuccessful': 'Upload successful',
  'stripeconnect_stripeconnect_uploading': 'Uploading',
  'stripeconnect_stripeconnect_upload_title': 'Upload Stripe Document',
  'stripeconnect_stripeconnect_selectTypeAndUploadImage': 'Select type and upload images',
  'stripeconnect_stripeconnect_veriftyYourIndentiryWithStripe': 'Verify your identity with Stripe',
  'stripeconnect_stripeconnect_identityVerification': 'Identity Verification',
  'stripeconnect_stripeconnect_uploadClearLegibleImages': 'Upload clear, legible images of your document',
  'stripeconnect_stripeconnect_select_type_title': 'Select Document Type',
  'stripeconnect_stripeconnect_front_side_title': 'Front Side',
  'stripeconnect_stripeconnect_back_side_title': 'Back Side',
  'stripeconnect_stripeconnect_tapToUpload': 'Tap to upload',
  'stripeconnect_stripeconnect_cameraOrGallery': 'Camera or Gallery',
  // ── Home ──
  'main_storedashboard_business_summary_title': 'Business Summary',
  'main_storedashboard_completed_title': 'Completed',
  'main_storedashboard_good_afternoon': 'Good Afternoon! 🌤️',
  'main_storedashboard_good_evening': 'Good Evening! 🌆',
  'main_storedashboard_good_night': 'Good Night! 🌙',
  'main_storedashboard_in_progress_title': 'In Progress',
  'main_storedashboard_low_stock_alert_message': 'products running low',
  'main_storedashboard_low_stock_alert_title': 'Low Stock Alert',
  'main_storedashboard_merchant_earnings_title': 'Merchant Earning',
  'main_storedashboard_order_amount_title': 'Order Amount',
  'main_storedashboard_out_of_stock_message': 'products unavailable',
  'main_storedashboard_out_of_stock_title': 'Out of Stock',
  'main_storedashboard_pending_title': 'Pending',
  'main_storedashboard_products_count_title': 'Products Count',
  'main_storedashboard_quick_action_add_product': 'Add Product',
  'main_storedashboard_quick_action_analytics': 'Analytics',
  'main_storedashboard_quick_action_manage_stock': 'Manage Stock',
  'main_storedashboard_quick_action_orders': 'Orders',
  'main_storedashboard_quick_actions_title': 'Quick Actions',
  'main_storedashboard_sales_month_title': 'This Month',
  'main_storedashboard_sales_summary_title': 'Sales Summary',
  'main_storedashboard_sales_today_title': 'Today',
  'main_storedashboard_sales_week_title': 'This Week',
  'main_storedashboard_store_earnings_title': 'Store Earning',
  'main_storedashboard_store_status_closed': 'Store is closed',
  'main_storedashboard_store_status_closed_goodDay': 'Good Day! 👋',
  'main_storedashboard_store_status_open': 'Currently accepting orders',
  'main_storedashboard_store_status_title': 'Store Status',
  'main_storedashboard_subtitle': 'Here\'s what\'s happening at {store_name} today.',
  'main_storedashboard_totalOrders': 'Total Orders',
  // ── Orders list ──
  'orders_ordersscreen_title': 'Orders',
  'orders_ordersscreen_tab_new': 'New',
  'orders_ordersscreen_tab_preparing': 'Preparing',
  'orders_ordersscreen_tab_ready': 'Ready',
  'orders_ordersscreen_past_cancelled_tab_title': 'Cancelled',
  'orders_ordersscreen_past_rejected_tab_title': 'Rejected',
  'orders_ordersscreen_past_auto_expired_tab_title': 'Expired',
  'orders_ordersscreen_past_completed_tab_title': 'Completed',
  'orders_ordersscreen_tab_today': 'Today',
  'orders_ordersscreen_tab_upcoming': 'Upcoming',
  'orders_ordersscreen_filter_pending_process_title': 'Pending Process',
  'orders_ordersscreen_filter_pending_pickup_title': 'Pending Pickup Verification',
  'orders_ordersscreen_filter_on_the_way_title': 'On The Way Orders',
  'orders_ordersscreen_items_title': 'Items:',
  'orders_ordersscreen_payment_title': 'Payment',
  'emptystate_emptystate_no_orders_title': 'No Orders Yet',
  'emptystate_emptystate_no_orders_message1': 'Try switching the status filter\\nor pull down to refresh',
  // ── Order detail and actions ──
  'orders_orderdetail_order_items_title': 'Order Items',
  'orders_orderdetail_order_status_title': 'Order Status',
  'orders_orderdetail_payment_details_title': 'Payment Details',
  'orders_orderdetail_payment_status_label': 'Payment Status',
  'orders_orderdetail_total_amount_label': 'Total Amount',
  'orders_orderdetail_item_qty_prefix': 'Qty: ',
  'orders_orderdetail_additional_notes_title': 'Additional Notes',
  'orders_orderdetail_chooseHowToAssign': 'Choose how you want to assign\\n a delivery driver',
  'orders_orderdetail_drivers_failed_title': 'Failed to load drivers',
  'orders_orderdetail_drivers_no_available_title': 'No Driver Available',
  'orders_orderdetail_drivers_no_available_subtitle': 'Try automatic assignment instead',
  'orders_orderdetail_select_drivers_hint': 'Tap to select multiple drivers',
  'orders_orderdetail_pickup_verification_subtitle': 'Ask the driver to provide the code to verify driver',
  'orders_orderdetail_otp_label': 'Enter Otp',
  'orders_ordersscreen_payment_method_title': 'Payment Method',
  'orders_ordersscreen_customerInfo': 'Customer Information',
  'orders_ordersscreen_customer_role': 'Customer',
  'orders_ordersscreen_callLabel': 'Call',
  'orders_ordersscreen_delivery_driver_title': 'Delivery Driver',
  'orders_ordersscreen_cooking_instructions_title': 'Cooking Instructions',
  'orders_ordersscreen_additional_instructions_title': 'Additional Instructions',
  'orders_ordersscreen_invoice_title_text': 'Invoice',
  'orders_ordersscreen_automatic_title': 'Automatic',
  'orders_ordersscreen_automatic_message': 'System picks the nearest available driver',
  'orders_ordersscreen_manual_title': 'Manual',
  'orders_ordersscreen_manual_message': 'Browse and select a driver yourself',
  'orders_ordersscreen_pickup_verification_button': 'Pickup Verification',
  'orders_ordersscreen_verify_otp_button': 'Verify OTP',
  'orders_ordersscreen_invalid_otp_message': 'Invalid OTP. Please try again.',
  'orders_selectdrivers_title': 'Select Drivers',
  'orders_selectdrivers_order_prefix': 'ORD-',
  'orders_selectdrivers_assign_button': 'Assign Drivers',
  // ── Products list ──
  'products_products_title': 'Products',
  'products_products_search_placeholder': 'Search products...',
  'products_products_all_category': 'All',
  'products_products_low_stock': 'Low Stock',
  'products_products_in_stock_status': 'In Stock',
  'products_products_low_stock_status': 'Low Stock',
  'products_products_out_of_stock_status': 'Out of Stock',
  'products_products_qty': 'qty',
  'products_products_noOutOfStockProducts': 'No out-of-stock products',
  'products_products_tryADifferentSearchOrClearTheFilters': 'Try a different search or clear the filters',
  'products_productdetail_variants_title': 'Variants',
  'emptystate_emptystate_no_products_title': 'No Products Found',
  'products_productdetail_dietary_veg': 'Veg',
  'products_productdetail_dietary_non_veg': 'Non-Veg',
  'products_products_variantsHint': 'Tap the variants count on a product to see and switch its variants.',
  // ── Product form ──
  'products_addproductscreen_title_add': 'Add Product',
  'products_addproductscreen_title_edit': 'Edit Product',
  'products_addproductscreen_productDetails': 'Product Details',
  'products_addproductscreen_upload_cover_title': 'Upload Cover Image',
  'products_addproductscreen_coverImage': 'Cover Image',
  'products_addproductscreen_tapToUploadCoverImage': 'Tap to upload cover image',
  'products_addproductscreen_jpgPngSupported': 'JPG, PNG supported',
  'products_addproductscreen_images_title': 'Product Images (Max 4)',
  'products_addproductscreen_name_required': 'Product name is required',
  'products_addproductscreen_sku_required': 'SKU is required',
  'products_addproductscreen_skuNumber': 'SKU Number',
  'products_addproductscreen_skuAutoGenerated': 'SKU Number (Auto-generated)',
  'products_addproductscreen_willBeGeneratedAutomatically': 'Will be generated automatically',
  'products_addproductscreen_category_required': 'Select category',
  'products_addproductscreen_sub_category_required': 'Select sub category',
  'products_addproductscreen_loadingSubcategories': 'Please wait, loading subcategories...',
  'products_addproductscreen_noSubcategoriesAvailable': 'No subcategories available',
  'products_addproductscreen_preparation_time_required': 'Enter preparation time',
  'products_addproductscreen_preparation_time_enterValidNumber': 'Enter a valid number',
  'products_addproductscreen_preparation_time_mustBeGreaterThan0': 'Must be greater than 0',
  'products_addproductscreen_sequence_required': 'Must be greater than 0',
  'products_addproductscreen_sequence_enterValidNumber': 'Enter a valid number',
  'products_addproductscreen_sequence_mustBeGreaterThan0': 'Must be greater than 0',
  'products_addproductscreen_timingAndOrder': 'Timing & Order',
  'products_addproductscreen_inventory': 'Inventory',
  'products_addproductscreen_inventory_title': 'Manage Inventory',
  'products_addproductscreen_inventory_message': 'Enable to track stock',
  'products_addproductscreen_inventory_Disbalemessage': 'Disable to track stock',
  'products_addproductscreen_select_food_type_title': 'Select Food Type',
  'products_addproductscreen_select_status_title': 'Select Status',
  'products_addproductscreen_saveProduct': 'Save Product',
  'products_products_name_title': 'Product Name',
  'products_products_name_placeholder': 'Enter product name',
  'products_products_category_title': 'Category',
  'products_products_category_placeholder': 'Select category',
  'products_products_sub_category_title': 'Sub Category',
  'products_products_sub_category_placeholder': 'Select sub category',
  'products_products_description_title': 'Description',
  'products_products_description_placeholder': 'Enter product description...',
  'products_products_ingredients_title': 'Ingredients',
  'products_products_ingredients_placeholder': 'Enter product ingredients...',
  'products_products_preparation_time_title': 'Preparation Time (mins)',
  'products_products_preparation_time_placeholder': 'e.g. 15',
  'products_products_sequence_title': 'Sequence',
  'products_products_sequence_placeholder': 'e.g. 1',
  'common_allscreen_saving': 'Saving...',
  'products_stockmanagement_update_title': 'Update Stock',
  // ── Variants and stock ──
  'products_addproductscreen_variant_add_title': 'Add Variant',
  'products_addproductscreen_variant_fillInVariantDetails': 'Fill in variant details',
  'products_addproductscreen_variant_edit_title': 'Edit Variant',
  'products_addproductscreen_variant_name_title': 'Variant Name',
  'products_addproductscreen_variant_name_placeholder': 'Enter variant name',
  'products_addproductscreen_variant_sku_barcode_title': 'SKU / Barcode',
  'products_addproductscreen_variant_sku_barcode_placeholder': 'Enter SKU / Barcode',
  'products_addproductscreen_variant_price_title': 'Price',
  'products_addproductscreen_variant_discount_percentage_title': 'Discount Percentage',
  'products_addproductscreen_variant_weight_title': 'Weight',
  'products_addproductscreen_variant_selectUnit': 'Select unit',
  'products_addproductscreen_variant_show_title': 'Show Title',
  'products_addproductscreen_variant_shown': 'Shown',
  'products_addproductscreen_variant_hidden': 'Hidden',
  'products_addproductscreen_variant_status_title': 'Variant Status',
  'products_addproductscreen_variant_enterAmount': 'Enter amount',
  'products_addproductscreen_variant_tapPlusToAddYourFirstVariant': 'Tap + to add your first variant.',
  'products_productvariantslist_add_button': 'Add Variant',
  'products_stockmanagement_noVariantsFound': 'No variants found',
  'storedetails_storeprofile_productAvailableTimeSlabs': 'Product available time slabs',
  'common_allscreen_savedSuccessfully': 'Saved successfully',
  'products_stockmanagement_sku_label': 'SKU:',
  'products_stockmanagement_units': 'Units',
  'products_stockmanagement_current': 'Current',
  'products_stockmanagement_afterUpdate': 'After Update',
  'products_stockmanagement_pricing': 'Pricing',
  'products_stockmanagement_productCost': 'Product Cost',
  'products_stockmanagement_sellingPrice': 'Selling Price',
  'products_stockmanagement_tapToChangeTheStockAmount': 'Tap +/− to change the stock amount',
  'products_stockmanagement_update_button': 'Update Stock',
  'products_stockmanagement_adjust_quantity_title': 'Adjust Quantity',
  'products_products_variant_plural': 'variants',
  'products_products_variant_singular': 'variant',
  // ── Product detail and options ──
  'products_productdetail_edit_button': 'Edit',
  'products_productdetail_startingFrom': 'Starting from',
  'products_productdetail_variesByVariantAndSelections': 'varies by variant & selections',
  'products_productdetail_option_groups_label': 'option groups',
  'products_productdetail_options_title': 'Options',
  'products_productvariantslist_stock_value': 'Stock:',
  'products_stockmanagement_active': 'Active',
  'products_stockmanagement_inActive': 'InActive',
  'products_addproductscreen_variant_mapOptions': 'Map Options',
  'products_addproductscreen_variant_saveOptions': 'Save Options',
  'products_addproductscreen_variant_noMappingOptionsFoundForThisProduct': 'No mapping options found for this product.',
  'products_addproductscreen_variant_pleaseAddOptionsFirst': 'Please add options first',
  'products_addproductscreen_variant_selectOptionsAndSetAmount': 'Select options and set amounts',
  // ── Categories and options ──
  'products_categories_title': 'Categories',
  'pos_posallcategoriesscreen_search_placeholder': 'Search categories...',
  'pos_posallcategoriesscreen_empty': 'No categories found',
  'emptystate_emptystate_no_results_title': 'No Results Found',
  'settings_settings_row_addNewOption': 'Add New Option',
  'settings_settings_row_EditOptions': 'Edit Options',
  'settings_settings_row_EditDetailsBelow': 'Edit Details Below',
  'settings_settings_row_deleteOption': 'Delete Option',
  'settings_settings_row_enterOptionName': 'Enter option name',
  'settings_settings_row_failedToLoadTypes': 'Failed to load types',
  'settings_settings_row_loadingTypes': 'Loading types...',
  'settings_settings_row_noOptions': 'No Options',
  'settings_settings_row_optionActivated': 'Option activated',
  'settings_settings_row_optionDeActivated': 'Option deactivated',
  'settings_settings_row_optionAddedSuccessfully': 'Option added successfully',
  'settings_settings_row_optionUpdatedSuccessfully': 'Option updated successfully',
  'settings_settings_row_optionDeletedSuccessfully': 'Option deleted successfully',
  'settings_settings_row_optionName': 'Option Name',
  'settings_settings_row_optionNameIsRequired': 'Option name is required',
  'settings_settings_row_optionType': 'Option Type',
  'settings_settings_row_pleaseselectAnOptionType': 'Please select an option type',
  'settings_settings_row_selectOptionType': 'Select option type',
  'settings_settings_row_status': 'Status',
  'products_products_update_button': 'Update',
  'products_productdetail_delete_button': 'Delete',
  'products_productdetail_actions_title': 'Actions',
  // ── Store profile and timings ──
  'storedetails_storeprofile_screen_title': 'Store Profile',
  'storedetails_storeprofile_editProfile': 'Edit Profile',
  'storedetails_storeprofile_basic_information_title': 'Basic Information',
  'storedetails_storeprofile_store_name_title': 'Store Name',
  'storedetails_storeprofile_store_name_placeholder': 'Enter store name',
  'storedetails_storeprofile_email': 'Email Address',
  'storedetails_storeprofile_email_placeholder': 'example@store.com',
  'storedetails_storeprofile_emailRequired': 'Email is required',
  'storedetails_storeprofile_invalidEmail': 'Invalid Email',
  'storedetails_storeprofile_phone_number_title': 'Phone Number',
  'storedetails_storeprofile_phone_placeholder': 'Phone number',
  'storedetails_storeprofile_address': 'Address',
  'storedetails_storeprofile_street_placeholder': 'Street address',
  'storedetails_storeprofile_street_required': 'Street address required',
  'storedetails_storeprofile_screen_landMark': 'LandMark',
  'storedetails_storeprofile_landMarkRequired': 'LandMark Required',
  'storedetails_storeprofile_screen_latitude': 'Latitude',
  'storedetails_storeprofile_screen_latitudePlaceHolder': 'e.g. 28.6139',
  'storedetails_storeprofile_screen_longitude': 'Longitude',
  'storedetails_storeprofile_screen_longitudePlaceHolder': 'e.g. 77.2090',
  'storedetails_storeprofile_screen_deliveryInformation': 'Delivery Information',
  'storedetails_storeprofile_screen_numberOfPersons': 'Number of Persons',
  'storedetails_storeprofile_screen_numberOfPersonsPlaceHolder': 'e.g. 2',
  'storedetails_storeprofile_noOfPersonsRequired': 'No Of Persons Required',
  'storedetails_storeprofile_screen_avgMealPrice': 'Avg. Meal Price',
  'storedetails_storeprofile_screen_avgMealPricePlaceHolder': 'e.g. 250',
  'storedetails_storeprofile_avgMealPriceRequired': 'Avg Meal price required',
  'storedetails_storeprofile_screen_deliveryTime': 'Delivery Time',
  'storedetails_storeprofile_screen_selectDeliveryTime': 'Select delivery time',
  'storedetails_storeprofile_deliveryTimeRequired': 'Delivery Time required',
  'storedetails_storeprofile_screen_otherServices': 'Other Services',
  'storedetails_storeprofile_screen_enableCustomPackagingOptions': 'Enable custom packaging options',
  'storedetails_storeprofile_screen_productAvailability': 'Product Availability',
  'storedetails_storeprofile_screen_setTimeSlabsForAvailability': 'Set time slabs for availability',
  'storedetails_storeprofile_storeLogo': 'Store Profile Image',
  'storedetails_storeprofile_pngOrJpgRecommended': 'PNG or JPG, recommended 512×512',
  'storedetails_storeprofile_change_logo_button': 'Change Store Profile',
  'storedetails_storeprofile_save_changes_button': 'Save Changes',
  'storedetails_storeprofile_contact_info_title': 'Contact Info',
  'storedetails_storeprofile_verified_badge': 'Verified Store',
  'storedetails_storeprofile_supportEmail': 'Support Email',
  'storedetails_storeprofile_supportPhone': 'Support Phone',
  'common_allscreen_joined': 'Joined',
  'storedetails_storetimeslots_title': 'Store Timings',
  'storedetails_storetimeslots_operating_hours_title': 'Operating Hours',
  'storedetails_storetimeslots_operating_hours_message': 'Set your store\'s operating hours. Customers will see when you\'re open.',
  'storedetails_storetimeslots_selectAll': 'Select All',
  'storedetails_storetimeslots_weekdays_only_button': 'Weekdays only',
  'storedetails_storetimeslots_open_time_value': 'Open Time:',
  'storedetails_storetimeslots_close_time_value': 'Close Time:',
  'storedetails_storetimeslots_save_changes_button': 'Save Changes',
  // ── Product availability time slabs ──
  'storedetails_storeprofile_noTimeSlabsYet': 'No Time Slabs Yet',
  'storedetails_storeprofile_createYourFirstProductAvailability': 'Create your first product availability\\ntime slab to control when items are visible',
  'storedetails_storeprofile_addFirstSlab': 'Add First Slab',
  'storedetails_storeprofile_allDay': 'All Day',
  'storedetails_storeprofile_custom': 'Custom',
  'storedetails_storeprofile_priority': 'Priority',
  'storedetails_storeprofile_timeSlabName': 'Time Slab Name',
  'storedetails_storeprofile_timeSlabNamePlaceHolder': 'e.g. Breakfast, Lunch…',
  'storedetails_storeprofile_timeSettings': 'Time Settings',
  'storedetails_storeprofile_availableAllDay': 'Available All Day',
  'storedetails_storeprofile_disableToSpecificHours': 'Disable to set specific hours',
  'storedetails_storeprofile_startTime': 'Start Time *',
  'storedetails_storeprofile_startTimeHint': '08:00 AM',
  'storedetails_storeprofile_endTime': 'End Time *',
  'storedetails_storeprofile_endTimeHint': '12:00 PM',
  'storedetails_storeprofile_selectStartTime': 'Select Start Time',
  'storedetails_storeprofile_selectEndTime': 'Select End Time',
  'storedetails_storeprofile_options': 'Options',
  'storedetails_storeprofile_customPricing': 'Custom Pricing',
  'storedetails_storeprofile_enableToSetACustomPrice': 'Enable to set a custom price',
  'storedetails_storeprofile_customPrice': 'Custom Price',
  'products_addproductscreen_variant_price_placeholder': 'Enter price',
  'storedetails_storeprofile_slabImage': 'Slab Image',
  'storedetails_storeprofile_tapToUploadImage': 'Tap to upload image',
  'storedetails_storeprofile_tapChangeToUpdate': 'Tap change to update',
  'storedetails_storeprofile_imageUploaded': 'Image uploaded',
  'storedetails_storeprofile_AddTimeSlab': 'Add Time Slab',
  'storedetails_storeprofile_editTimeSlab': 'Edit Time Slab',
  'storedetails_storeprofile_saveTimeSlab': 'Save Time Slab',
  'storedetails_storeprofile_updateTimeSlab': 'Update Time Slab',
  'storedetails_storeprofile_delete_confirmationMessage': 'Are you sure you want to Delete?',
  'storedetails_storeprofile_timeSlabNameIsRequired': 'Time Slab Name is required',
  'storedetails_storeprofile_priorityIsRequired': 'Priority is required',
  'storedetails_storeprofile_startTimeRequired': 'Start time required',
  'storedetails_storeprofile_endTimeRequired': 'End time required',
  'storedetails_storeprofile_priceIsRequired': 'Price required',
  'common_allscreen_deleted_successfully': 'Deleted successfully',
  // ── Earnings ──
  'financialsmodule_financialsmodule_basedOnSelectedPeriod': 'Based on selected period',
  'financialsmodule_financialsmodule_cartAmount': 'Cart Amount',
  'financialsmodule_financialsmodule_deliveryCharges': 'Delivery',
  'financialsmodule_financialsmodule_merchant_earning_title': 'Merchant Earning',
  'financialsmodule_financialsmodule_noEarningsYet': 'No Earnings Yet',
  'financialsmodule_financialsmodule_orderBreakDown': 'Order Breakdown',
  'financialsmodule_financialsmodule_order_amount_title': 'Order Amount',
  'financialsmodule_financialsmodule_order_id': 'Order #',
  'financialsmodule_financialsmodule_otherCharges': 'Other Charges',
  'financialsmodule_financialsmodule_store_earning_title': 'Store Earning',
  'financialsmodule_financialsmodule_tax_deducted_title': 'Tax Deducted',
  'financialsmodule_financialsmodule_totalStoreEarnings': 'Total Store Earnings',
  'financialsmodule_financialsmodule_total_orders_title': 'Total Orders',
  'financialsmodule_financialsmodule_tryAdjustingDateRange': 'Try adjusting the date range\\nto see your transactions.',
  'pos_posordersfiltersheetscreen_date_range': 'Date Range',
  'common_allscreen_ok_button': 'OK',
  // ── Wallet and cashout ──
  'financialsmodule_financialsmodule_all_transactions_title': 'All Transactions',
  'financialsmodule_financialsmodule_no_transactions_found_message': 'No transactions found',
  'financialsmodule_financialsmodule_trackYourEarnings': 'Track your earnings',
  'financialsmodule_financialsmodule_header_available_balance_title': 'Available Balance',
  'financialsmodule_financialsmodule_cashout_history_title': 'Cashout History',
  'financialsmodule_financialsmodule_cashout_history_requestCashout': 'Request Cashout',
  'financialsmodule_financialsmodule_cashout_history_enterAmountToWithdraw': 'Enter amount to withdraw',
  'financialsmodule_financialsmodule_enter_amount_title': 'Enter Withdrawal Amount',
  'financialsmodule_financialsmodule_cashout_history_submitRequest': 'Submit Request',
  'financialsmodule_financialsmodule_submitting': 'Submitting…',
  'financialsmodule_financialsmodule_cashout_history_requestSubmittedSuccessfully': 'Request submitted successfully',
  'financialsmodule_financialsmodule_no_cashout_transactions_message': 'No cashout transactions',
  'financialsmodule_financialsmodule_transaction_id_title': 'Transaction ID',
  'financialsmodule_financialsmodule_cashout_history_amount': 'Amount',
  'financialsmodule_financialsmodule_cashout_history_actionBy': 'Action By',
  'financialsmodule_financialsmodule_cashout_history_comment': 'Comment',
  'pos_posreceiptscreen_label_date_short': 'Date',
  'pos_posreceiptscreen_label_type': 'Type',
  // ── Analytics ──
  'storedetails_storeanalytics_range_daily_title': 'Daily',
  'storedetails_storeanalytics_range_weekly_title': 'Weekly',
  'storedetails_storeanalytics_range_monthly_title': 'Monthly',
  'storedetails_storeanalytics_total_revenue_title': 'Total Revenue',
  'storedetails_storeanalytics_total_orders_title': 'Total Orders',
  'storedetails_storeanalytics_avg_order_value_title': 'Avg Order Value',
  'storedetails_storeanalytics_earnings_split_title': 'Earnings Split',
  'storedetails_storeanalytics_merchant': 'Merchant',
  'storedetails_storeanalytics_store': 'Store',
  'storedetails_storeanalytics_sales_overview_title': 'Sales Overview',
  // ── Settings ──
  'settings_settings_row_ownerAccount': 'Owner Account',
  'settings_settings_section_preferences': 'Preferences',
  'settings_settings_row_store_profile_message': 'Name, address, contact info',
  'settings_settings_row_store_timings_message': 'Operating hours',
  'settings_settings_row_categories_message': 'Manage product categories',
  'settings_settings_row_optionsDesc': 'Add Options',
  'settings_settings_row_detailEarningReport': 'Detailed earnings report',
  'settings_settings_row_viewAllWalletActivity': 'View all wallet activity',
  'settings_settings_row_cashoutRequestDesc': 'Withdraw your earnings',
  'settings_settings_row_past_orders_title': 'Past Orders',
  'settings_settings_row_change_language_title': 'Change Language',
  'settings_settings_row_change_theme_title': 'Change Color Theme',
  'settings_settings_toggle_theme_message': 'Light / Dark mode',
  'themeselector_styleguide_appearance_system': 'System',
  'themeselector_styleguide_appearance_light': 'Light',
  'themeselector_styleguide_appearance_dark': 'Dark',
  'settings_settings_logout_title': 'Logout',
  'auth_loginscreen_merchant_logout_title': 'Log Out',
  'auth_loginscreen_merchant_logout_message': 'Are you sure you want to log out?',
  'settings_settings_row_yesLogOut': 'Yes,Log Out',
  'storedetails_storeprofile_delete_account_title': 'Delete Account',
  'storedetails_storeprofile_delete_account_message': 'This action is permanent. All your store data, inventory, and history will be wiped. Do you really want to continue?',
  'storedetails_storeprofile_delete_account_confirm_button': 'Delete Permanently',
  'settings_settings_row_forAccountDelete': 'For Account Delete',
  // ── Membership ──
  'membership_membershipscreen_current_plan': 'Current Plan',
  'membership_membershipscreen_recommended': 'Recommended',
  'membership_membershipscreen_subscribe': 'Subscribe',
  'membership_membershipscreen_orders_included': '%d orders included',
  'membership_membershipscreen_max_order_value': 'Max order value %s',
  'membership_membershipscreen_choose_payment': 'Choose payment method',
  'membership_membershipscreen_pay': 'Pay %s',
  'membership_membershipscreen_success': 'Membership purchased successfully',
  'membership_membershipscreen_no_plans': 'No membership plans available',
  'membership_membershipscreen_no_payment_options': 'No payment options available',
  'membership_membershipscreen_period_day': '1 Day',
  'membership_membershipscreen_period_days': '%d Days',
  'membership_membershipscreen_period_month': '1 Month',
  'membership_membershipscreen_period_months': '%d Months',
  'membership_membershipscreen_period_year': '1 Year',
};